name: diggerdug # check to see if it's available
version: '1.7' # this is freakin' awesome
summary: A python script for checking hosts # 79 char long summary
description: |
  This simple script runs dig, nmap and netcat in sequence to check a host.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs

apps:
  diggerdug:
    # dang it snapcraft, find the right executable!!
    command: python3 $SNAP/bin/diggerdug.py
    environment: 
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/
    plugs:
      - home
      - network
     
parts: 
  my-part:
    source: https://github.com/kz6fittycent/digger-dug
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      - netcat-traditional
      - nmap
      - dnsutils
      
    stage-packages:
      - python3
      - netcat-traditional
      - nmap
      - dnsutils
  
  publish:
    plugin: copy
    files:
      ./diggerdug.py: bin/diggerdug.py
